NAME = CAMLHI
DESCRIPTION = "hello from ocaml"
COMPRESSED = NO

SRCDIR = .
BINDIR = .

CFLAGS = -Wall -Wextra -O3 -Wno-unused-parameter -Wno-unused-parameter -Wno-unused-variable -Wno-unused-label

include $(shell cedev-config --makefile)
