NAME = CAMLHELLO
DESCRIPTION = "hello from ocaml"
COMPRESSED = NO

SRCDIR = .
BINDIR = .

CFLAGS = -Wall -Wextra -Oz -Wno-unused-parameter -Wno-unused-parameter -Wno-unused-variable -Wno-unused-label

include $(shell cedev-config --makefile)
