external begin_ : unit -> unit = "caml_gfx_begin"
external end_ : unit -> unit = "caml_gfx_end"
external set_draw_buffer : unit -> unit = "caml_gfx_set_draw_buffer"
external swap_draw : unit -> unit = "caml_gfx_swap_draw"
external fill_screen : int -> unit = "caml_gfx_fill_screen"
external set_color : int -> unit = "caml_gfx_set_color"
external line : int -> int -> int -> int -> unit = "caml_gfx_line"
